### ISSUE TITLE
Illegal reflective access warning when using "_parameter.containsKey() and Collections.singletonMap

### ISSUE THREAD

**Issue by Farbfetzen** [jkuhnert/ognl#143]
Greetings,
I first reported this issue in https://github.com/mybatis/mybatis-3/issues/2421 but then I realized it might be more appropriate here.

When I have some sql statements containing `<if test="_parameter.containsKey('foo')">` and the parameters are in a `Collections.singletonMap` I get the following warning in the console:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ognl.AccessibleObjectHandlerPreJDK9 (file:/C:/Users/shenz/.m2/repository/ognl/ognl/3.3.1/ognl-3.3.1.jar) to method java.util.Collections$SingletonMap.containsKey(java.lang.Object)
WARNING: Please consider reporting this to the maintainers of ognl.AccessibleObjectHandlerPreJDK9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
This does not happen when using `java.util.Map`.

I am using Java 11.0.13.

**Comment by harawata** [comment]
@Farbfetzen , 
Thank you for re-filing the issue.

@lukaszlenart ,
Here are some additional info.

The following test yields the "illegal reflective access" warning on Java 9+ and an exception on Java 16+ [1].

```java
@Test
public void testMapContainsKey() throws Exception {
  Map defaultContext = new HashMap<>();
  Map<String, Object> root = new HashMap<>();
  root.put("map", Collections.singletonMap("key", "value"));
  assertTrue((Boolean) Ognl.getValue("map.containsKey('key')", defaultContext, root));
}
```

This happens because OGNL calls the `containsKey()` method of the private class `java.util.Collections$SingletonMap`.
The method OGNL should call is the one that is defined in `java.util.Map`.

The [comment on the relevant line](https://github.com/jkuhnert/ognl/blob/b8ce95cd2f8df5312b0086fd58a10ea09cad467d/src/main/java/ognl/OgnlRuntime.java#L1789) seems to imply that this behavior is intentional, but can you think of a case where it is necessary (or more appropriate) to call "the most specific" method rather than the same method defined in the superclass/interface? (there seems to be no test case)
I'm working on a fix which basically alters the priority when choosing the method to call.

<details>
<summary>
[1]  Stack Trace</summary>

```
java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$SingletonMap.containsKey(java.lang.Object) accessible: module java.base does not "opens java.util" to unnamed module @11739fa6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at ognl.AccessibleObjectHandlerPreJDK9.setAccessible(AccessibleObjectHandlerPreJDK9.java:58)
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:1211)
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1962)
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:2038)
	at ognl.ASTMethod.getValueBody(ASTMethod.java:97)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.ASTChain.getValueBody(ASTChain.java:141)
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at ognl.SimpleNode.getValue(SimpleNode.java:258)
	at ognl.Ognl.getValue(Ognl.java:586)
	at ognl.Ognl.getValue(Ognl.java:688)
	at ognl.Ognl.getValue(Ognl.java:658)
	at ognl_default_method.OgnlDefaultMethodTest.testMapContainsKey(OgnlDefaultMethodTest.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```
</details>

**Comment by lukaszlenart** [comment]
Probably in case of interfaces it makes sense to call interface version, but I think we also need to cover the below case

```java
interface I {
  boolean doSth();
}

class A implements I {
  public boolean doSth() { return true ; }
}

class B extends A {
  public boolean doSth() { return false; }
}
```

**Comment by harawata** [comment]
Thank you, @lukaszlenart !

Even when the `java.lang.reflect.Method` references the interface's method (i.e. `I#doSth()`), `java.lang.reflect.Method#invoke()` will return the correct value depending on the first argument (i.e. the target instance).
It should be OK if the following test passes, right?

```java
@Test
public void should() throws Exception {
    Map defaultContext = new HashMap<>();
    Map<String, Object> root = new HashMap<>();
    root.put("a", new A());
    root.put("b", new B());
    assertTrue((Boolean) Ognl.getValue("a.doSth()", defaultContext, root));
    assertFalse((Boolean) Ognl.getValue("b.doSth()", defaultContext, root));
}
```

Please let me know if I am misunderstanding the issue.

**Comment by lukaszlenart** [comment]
I think you are right, but we can try to play with the scoring to score private methods lower - maybe that will solve the problem.

**Comment by harawata** [comment]
@lukaszlenart ,

I found a case where calling subclass method is more appropriate.

```java
@Test
public void shouldInvokeSyntheticBridgeMethod() throws Exception {
    StringBuilder root = new StringBuilder("abc");
    Assert.assertEquals((int) 'b',
            Ognl.getValue("codePointAt(1)", defaultContext, root));
}
```

I had considered tweaking the score, but this comparison seems to make sense only when two methods have the same score and (almost) same signature.
So, for now, the plan is to use the public one over non-public one.
Please take a look at #144 when you have time.

**Comment by lukaszlenart** [comment]
@harawata you are right, it's even clearer to call the public method in such case 👏
