### ISSUE TITLE
Compile expression throws no such class with custom ClassResolver

### ISSUE THREAD

**Issue by sfyumi** [jkuhnert/ognl#76]
I impliment a ClassResolver that imports a custom package other than `java.lang`.
It throws when compiling expression calling static method of class under my custom package.

Express is like this `@Calbit@cal(x)`, and the package path is `cn.agentd.ognl.util`.

stacktrace
```
Exception in thread "main" javassist.CannotCompileException: [source error] no such class: Calbit
	at javassist.CtBehavior.setBody(CtBehavior.java:474)
	at javassist.CtBehavior.setBody(CtBehavior.java:440)
	at ognl.enhance.ExpressionCompiler.generateGetter(ExpressionCompiler.java:553)
	at ognl.enhance.ExpressionCompiler.compileExpression(ExpressionCompiler.java:419)
	at ognl.OgnlRuntime.compileExpression(OgnlRuntime.java:435)
	at ognl.Ognl.compileExpression(Ognl.java:141)
	at cn.agentd.ognl.Demo.main(Demo.java:27)
Caused by: compile error: no such class: Calbit
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:683)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at javassist.compiler.JvstTypeChecker.atCastToWrapper(JvstTypeChecker.java:138)
	at javassist.compiler.JvstTypeChecker.atCastExpr(JvstTypeChecker.java:110)
	at javassist.compiler.ast.CastExpr.accept(CastExpr.java:59)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
	at javassist.compiler.CodeGen.compileExpr(CodeGen.java:253)
	at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:641)
	at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:443)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:393)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
	at javassist.compiler.Javac.compileBody(Javac.java:228)
	at javassist.CtBehavior.setBody(CtBehavior.java:466)
	... 6 more
```

**Comment by lukaszlenart** [comment]
Did you try to use `@full.package.name.Calbit@cal(x)`?
